//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smaaahh_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int CarId { get; set; }
        public int PlaceNumber { get; set; }
        public string Model { get; set; }
        public string CarPlate { get; set; }
        public int DriverId { get; set; }
    
        public virtual Drivers Drivers { get; set; }
    }
}
